### PR TITLE
Stop WebSocketClient after connection is closed

### PR DESCRIPTION
**Pull request by andyhorng**
The WebSocketClient does not stop properly when automation is closed.

### CODE REVIEW

**Comment by aviflax** [comment]
I’ve been working on this too, in a local branch. Maybe I could contribute tests to your branch… would you be interested in a PR that points to this branch in your fork?

**Comment by andyhorng** [comment]
@aviflax Sure! Thanks your help.

**Comment by aviflax** [comment]
Great. I’m at an offsite today, but I’ll try to open the PR either tonight or tomorrow (British Summer Time)

**Comment by aviflax** [comment]
@andyhorng please see https://github.com/andyhorng/clj-chrome-devtools/pull/1 — sorry for the delay!

**Review by aviflax — APPROVED** [review]
👍

**Comment by aviflax** [comment]
@tatut any interest?

**Pull request merged**
